Feature/#20 mobile hero
marceloglacial/2021-leal-e-clementino pull request #34
Opened 2021-03-05 18:23 UTC by dutraneto

Hey, @marceloglacial (Hero section) ready for review.

2021-03-05 20:19 UTC, marceloglacial requested changes
Good job. 
Two things to fix:

1) Header heigh is 100vh and overlapping the content (I missed the on the other review)
<img width="1792" alt="Screen Shot 2021-03-05 at 3 15 00 PM" src="https://user-images.githubusercontent.com/11657599/110168721-94002980-7dc5-11eb-873e-c7ff048d6df0.png">

2) Filter props has a few knowing issues, so try to avoid it. (https://caniuse.com/?search=filter). You can use a pseudo element (:before) to create the brightness effect (another thing that I missed from the laters reviews. Sorry about that)

<img width="1792" alt="Screen Shot 2021-03-05 at 3 15 36 PM" src="https://user-images.githubusercontent.com/11657599/110169020-0ffa7180-7dc6-11eb-90c7-635ec7015928.png">

2021-03-05 23:50 UTC, dutraneto commented
> Good job.
> Two things to fix:
> 
> 1. Header heigh is 100vh and overlapping the content (I missed the on the other review)
> 
> <img alt="Screen Shot 2021-03-05 at 3 15 00 PM" width="1792" src="https://user-images.githubusercontent.com/11657599/110168721-94002980-7dc5-11eb-873e-c7ff048d6df0.png">
> 
> 1. Filter props has a few knowing issues, so try to avoid it. (https://caniuse.com/?search=filter). You can use a pseudo element (:before) to create the brightness effect (another thing that I missed from the laters reviews. Sorry about that)
> 
> <img alt="Screen Shot 2021-03-05 at 3 15 36 PM" width="1792" src="https://user-images.githubusercontent.com/11657599/110169020-0ffa7180-7dc6-11eb-90c7-635ec7015928.png">

It was a good catch. I was supposed to fix that and ended up forgetting it.

2021-03-06 00:56 UTC, dutraneto commented
#20 ready after changes were made. Please, review it as soon as possible. Thank you!

2021-03-08 13:34 UTC, marceloglacial approved these changes

2021-03-08 13:39 UTC, marceloglacial approved these changes

2021-03-08 13:39 UTC, marceloglacial commented on src/styles/components/_hero.scss
> -        filter: brightness(60%);
Where's the alternative code? 🤔

2021-03-08 13:39 UTC, marceloglacial commented on src/styles/components/_hero.scss
> -        filter: brightness(60%);
Nevermind. I forgot I removed the background on the prototype hahaha Sorry. My bad :)

2021-03-08 15:41 UTC, merged