Feature/25 mobile socios
marceloglacial/2021-leal-e-clementino pull request #42
Opened 2021-03-09 14:46 UTC by dutraneto

@marceloglacial, this #40  fixes found issues (#41, #25). Please, review it.

2021-03-09 14:58 UTC, marceloglacial requested changes
Add word-break on the text to avoid the logo overlapping. 

<img width="391" alt="Screen Shot 2021-03-09 at 9 54 39 AM" src="https://user-images.githubusercontent.com/11657599/110490092-f99e2f80-80bd-11eb-9836-57cc56467ad3.png">

2021-03-09 14:58 UTC, marceloglacial commented on src/styles/components/_card.scss
> +    height: 198px;
Use min-height. Fixed height could cause an issue when the card has more information

2021-03-09 15:00 UTC, dutraneto commented on src/styles/components/_card.scss
> +    height: 198px;
Sounds good

2021-03-09 15:19 UTC, dutraneto commented on src/styles/components/_card.scss
> +    height: 198px;
![Screen Shot 2021-03-09 at 10 16 56 AM](https://user-images.githubusercontent.com/18724070/110493492-a8436f80-80c0-11eb-861f-9ef3029c62d8.png)

It will be weird breaking the email. Logo has been set as a bg-img. I can leave like that only for  "<=320px" or also lower the logo height to avoid its overlapping. What that sounds better for you?

2021-03-10 00:48 UTC, marceloglacial approved these changes

2021-03-10 01:35 UTC, merged