Set map height for mobile resolutions
marceloglacial/2021-leal-e-clementino pull request #44
Opened 2021-03-10 02:10 UTC by dutraneto

@marceloglacial, please review issue #24. Appreciated.

2021-03-10 02:15 UTC, marceloglacial requested changes
Header overlapping the address when you click on the nav to jump to "localicação"

<img width="847" alt="Screen Shot 2021-03-09 at 9 14 41 PM" src="https://user-images.githubusercontent.com/11657599/110565409-78c25080-811c-11eb-90f1-cb82490ada8c.png">

<img width="497" alt="Screen Shot 2021-03-09 at 9 13 40 PM" src="https://user-images.githubusercontent.com/11657599/110565362-5f210900-811c-11eb-9e4c-816a2567eceb.png">

2021-03-10 02:18 UTC, dutraneto commented
I will take a look right now!

2021-03-10 02:25 UTC, dutraneto commented
<img width="425" alt="Screen Shot 2021-03-09 at 9 24 34 PM" src="https://user-images.githubusercontent.com/18724070/110566373-ed49bf00-811d-11eb-984a-76fec48b99b0.png">

Hey, would you mind being more specific? I cannot see that issue. Thank you!

2021-03-10 02:32 UTC, marceloglacial commented
Please, check out the video

https://user-images.githubusercontent.com/11657599/110566988-d061bb80-811e-11eb-8469-6e7c9e0d1d6d.mov

2021-03-10 02:38 UTC, dutraneto commented
> Please, check out the video
> 
>  Screen.Recording.2021-03-09.at.9.30.33.PM.mov

Understood.

2021-03-10 02:53 UTC, dutraneto commented
It is done

2021-03-10 02:58 UTC, marceloglacial requested changes

2021-03-10 02:58 UTC, marceloglacial commented on src/styles/components/location.scss
> +        height: calc(100vh - 20.625rem);
Solved for table. The issue persist on mobile. 

<img width="541" alt="Screen Shot 2021-03-09 at 9 57 57 PM" src="https://user-images.githubusercontent.com/11657599/110569436-84b11100-8122-11eb-80a7-3a0b85385484.png">

2021-03-10 03:04 UTC, marceloglacial commented on src/styles/components/location.scss
> +        height: calc(100vh - 20.625rem);
TIP: add the header height to the section padding instead to change the height ;)

2021-03-10 14:00 UTC, dutraneto commented
It should be working now. Thank you for your tip =)

2021-03-12 17:52 UTC, marceloglacial approved these changes

2021-03-12 19:33 UTC, merged